#!/usr/bin/env bash
# ci/linter/lint-astgrep.sh -- ast-grep structural sink sweep over src/*.[ch].
#
# Structural, not textual. The other C checkers here read the file as tokens
# (flawfinder's risky-API list) or as a whole translation unit (cppcheck,
# clang-tidy); ast-grep reads it as a PARSE TREE, so a rule can say "memcpy
# whose third argument is a sizeof of a pointer" and mean it -- a shape grep
# cannot express and a TU-level analyzer will not report unless it can also
# prove the overflow. That is the gap this fills: cheap, shape-level sinks,
# checked on every commit rather than in the nightly deep lane.
#
# Ruleset is ci/ast-grep/: rules/own/ (this superrepo's C and nginx rules) plus
# rules/vendor/ (the C/C++ slice of CodeRabbit's Apache-2.0 `essentials` pack,
# CWE-tagged -- the rules the bot itself runs on a pull request, so a hit here
# is a review comment caught before the push). Both are GENERATED by
# tools/vendor-astgrep-rules.py; refresh with that script, never by hand.
#
#   -c ci/ast-grep/sgconfig.yml is LOAD-BEARING, do not drop it to let ast-grep
#       "find the config itself". ast-grep resolves sgconfig.yml by walking UP
#       from the working directory. Without -c, this checker binds to
#       /opt/myguard/sgconfig.yml while the clone sits inside the superrepo,
#       and binds to NOTHING in a standalone clone -- scanning against an empty
#       ruleset and reporting green. The rules are vendored into ci/ast-grep/
#       precisely so this gate is self-contained wherever the clone lives.
#
# THE GATE IS THE PROMOTED LIST, NOT THE RULESET. ast-grep has no severity
# threshold flag (unlike `semgrep --severity`) and exits non-zero only on
# `error`, so the gate is built by PROMOTING named rules with --error=;
# everything else stays advisory -- printed, never blocking.
#
# That split is what makes this gateable at all. Measured across every module
# repo 2026-08-08: 318 of 368 findings are note[nginx-unchecked-palloc], which
# in nginx C is frequently legitimate (call sites propagate NULL deliberately).
# Gating the note tier would land every repo red on arrival and train everyone
# to --no-verify -- the same failure mode the shellcheck note in lint-sh.sh
# describes. A rule joins PROMOTED only after its findings are measured on real
# trees and confirmed real.
#
# Keep PROMOTED identical to the --error= list in .pre-commit-config.yaml's
# ast-grep hook. Two gates disagreeing about what blocks is worse than one:
# the hook passes, CI fails, and the difference is invisible in both outputs.
#
# A PROMOTED NAME THAT DOES NOT EXIST IS SILENTLY IGNORED. Verified against
# ast-grep 0.44.1 on 2026-08-10: `--error=no-such-rule-xyz` exits 0 without a
# word of complaint, so a typo (or a rule renamed by a ruleset refresh) does not
# fail loudly -- it quietly un-gates that rule and the checker keeps reporting
# green. Nothing in ast-grep catches this, which is why every name in PROMOTED
# is checked against the ruleset below BEFORE the scan runs. Do not drop that
# check on the grounds that ast-grep "would surely error": it does not.
#
# Usage: ci/linter/lint-astgrep.sh [files...]   Env: LINT_MODE=staged|all
# Exit:  0 clean, 1 a promoted rule fired, 2 ast-grep missing, config gone, or
#        a PROMOTED name that no rule defines.
# Extend: add rules via tools/vendor-astgrep-rules.py. Promote one by adding it
# to PROMOTED here AND to the pre-commit hook, once its findings are confirmed.

# shellcheck source=ci/linter/lib.sh
. "$(git rev-parse --show-toplevel)/ci/linter/lib.sh"

# Rules whose findings are confirmed real and therefore BLOCK. Everything else
# in the ruleset still runs and still prints, at its own severity.
PROMOTED=(
    c-alloc-mul-overflow
    c-memcpy-sizeof-pointer
    c-sizeof-wrong-operand
    c-unbounded-string-copy
    c-format-string
    c-shell-exec
)

mapfile -t FILES < <(lint_files '^src/.*\.[ch]$' "$@")
[ "${#FILES[@]}" -gt 0 ] || { echo "lint-astgrep: no C files to check"; exit 0; }

echo "lint-astgrep: ${#FILES[@]} file(s)"

need ast-grep "see ci/linter/install-linters.sh (pinned upstream binary)"

CONFIG="ci/ast-grep/sgconfig.yml"
# A missing config is exit 2 ("could not run"), never a clean pass. Without
# this, a deleted or unported ci/ast-grep/ makes ast-grep scan an empty ruleset
# and exit 0 -- the exact green-while-checking-nothing failure the -c flag
# exists to prevent.
[ -f "$CONFIG" ] || die "$CONFIG missing -- regenerate with tools/vendor-astgrep-rules.py"

# Every promoted name must actually be defined by a rule, or the promotion is a
# no-op that reads as a gate (see the header note). Rule ids are the `id:` field
# of the vendored YAML; the ruleset is generated, so this stays a plain scan of
# ci/ast-grep/rules/ rather than anything that needs ast-grep to cooperate.
mapfile -t KNOWN < <(grep -rhE '^id:[[:space:]]*' ci/ast-grep/rules/ \
                     | sed -E 's/^id:[[:space:]]*//; s/[[:space:]]*$//' | sort -u)
[ "${#KNOWN[@]}" -gt 0 ] || die "no rule ids under ci/ast-grep/rules/ -- ruleset empty or unported"

unknown=""
for r in "${PROMOTED[@]}"; do
    printf '%s\n' "${KNOWN[@]}" | grep -qx "$r" || unknown="$unknown $r"
done
[ -z "$unknown" ] || die "PROMOTED names no rule defines:$unknown
       | ast-grep ignores an unknown --error= silently, so these gate NOTHING.
       | Fix the spelling or drop them; keep .pre-commit-config.yaml in step."

ERRFLAGS=()
for r in "${PROMOTED[@]}"; do ERRFLAGS+=("--error=$r"); done

say "ast-grep (${#PROMOTED[@]} promoted rule(s) block; rest advisory)"
ast-grep scan -c "$CONFIG" "${ERRFLAGS[@]}" "${FILES[@]}"
rc=$?

# 0 clean, 1 a promoted rule fired. Anything else is ast-grep failing to run
# (6 = config error, verified 2026-08-10), which is "could not run", not clean.
case "$rc" in
    0|1) exit "$rc" ;;
    *)   die "ast-grep exited $rc -- could not run (config error?), not a verdict" ;;
esac
